### ISSUE TITLE
Too much DEB dependencies

### ISSUE THREAD

**Issue by Symbian9** [ayoy/fontedit#4]
l just trying to install DEB under Debian 10 buster, but `fontedit_1.1.0-1_amd64.deb` and it asks me to install 36 packages (`cmake`, many `*-dev` packages, etc.) according dependency list:

```
Depends: qt5-default (>= 5.9), libc6 (>= 2.14), libgcc1 (>= 1:3.0), libqt5core5a (>= 5.9.0~beta), libqt5gui5 (>= 5.6.0~beta), libqt5network5 (>= 5.9.0~beta), libqt5widgets5 (>= 5.2.0), libstdc++6 (>= 5.2)
Pre-Depends: cmake (>= 3.9), g++ (>= 7.4)
```

Does all those dependency really needed for binary version of `fontedit`?

**Comment by ayoy** [comment]
Certainly not. I confused `Predepends` with packages required to compile the sources.

I'm coming from Gentoo background and there was a concept of DEPEND and RDEPEND, meaning "packages required to compile & install" and "packages required to run", respectively.

Will fix it promptly.

**Comment by ayoy** [comment]
Please check now with the `fontedit_1.1.0-2_amd64.deb` from the [releases page]( https://github.com/ayoy/fontedit/releases/tag/v1.1.0).

**Comment by Symbian9** [comment]
Well, `fontedit_1.1.0-2_amd64.deb` now asks me to install not 36, but 32 additional packages.

Does `qt5-default (>= 5.9)` is really should be dependency for this DEB?

**Comment by ayoy** [comment]
You're right. I was underestimating dpkg automatic dependency resolution, plus the `qt5-default` is definitely not needed. There's a v3 deb waiting for you in the releases page.

Thanks for your help.
