### ISSUE TITLE
Doesn't work on MacOS Mojave

### ISSUE THREAD

**Issue by Qix-** [ayoy/fontedit#5]
Is there a reason why this can only be run on Catalina?

**Comment by ayoy** [comment]
Hi, so I haven't specify the deployment target and it defaulted to my OS which is Catalina. I updated it to include Mojave. Please try the new DMG (`Fontedit-1.1.0-2.dmg`) that I uploaded to the [releases page](https://github.com/ayoy/fontedit/releases/tag/v1.1.0).

**Comment by Qix-** [comment]
Yep, that works. Thanks!
