### ISSUE TITLE
Installed fonts not shown (Windows)

### ISSUE THREAD

**Issue by ChrisH861** [ayoy/fontedit#7]
I can't see any custom fonts that I have installed, they are shown on the windows settings font page.
What am I doing wrong?

**Comment by ayoy** [comment]
Is there a chance that your custom fonts are not fixed-width? FontEdit only supports fixed-width fonts, and filters the fonts list accordingly, so perhaps that's the case.

If unsure, you can try downloading Ubuntu Fonts Family here:
https://assets.ubuntu.com/v1/0cef8205-ubuntu-font-family-0.83.zip
and the Ubuntu Mono font should be visible for FontEdit.

**Comment by ChrisH861** [comment]
ah yeah that was it, thanks

**Comment by mix3d** [comment]
Is there any way to convert a font to fixed width? Found a really nice one, but it's not fixed width
